##### BEGIN external-mapped/Dockerfile/image-header #####
FROM confluentinc/cp-ksql-server:5.4.0
##### END external-mapped/Dockerfile/image-header #####

##### BEGIN image/Dockerfile/build-instructions #####
USER root
RUN apt-get update && apt-get install -y --force-yes gettext && rm -rf /var/cache/apt/*
RUN wget -O jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 && chmod +x ./jq && cp jq /usr/bin
##### END image/Dockerfile/build-instructions #####

##### BEGIN external/Dockerfile/conteco #####
COPY ./ /conteco/repo/
##### END external/Dockerfile/conteco #####

##### BEGIN external-mapped/Dockerfile/labels-footer #####
LABEL io.vcweb.schema-version="1.0" \
      io.vcweb.realm="vcwebio" \
      io.vcweb.ecosystem="conteco" \
      io.vcweb.type="external" \
      io.vcweb.name="ksql_server" \
      io.vcweb.tag="5.4.0" \
      io.vcweb.base="confluentinc/cp-ksql-server:5.4.0" \
      io.vcweb.build="external-mapped" \
      io.vcweb.label="external.ksql_server - ContEco" \
      io.vcweb.description="Confluent ksql server image with ContEco external prerequisites installed." \
      io.vcweb.repository="/conteco/repo"
##### END external-mapped/Dockerfile/labels-footer #####
